version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install
          command: |
            python -m venv venv
            . venv/bin/activate
            python setup.py install
      - run:
          name: Test
          command: |
            . venv/bin/activate
            python setup.py test
